### ISSUE TITLE
Podcast med Evetro (trondheim startup)

### ISSUE THREAD

**Issue by koiski** [BartJS/podcast#2]
Mulige temaer vi kan snakke om: 

- Living on the edge - Nyeste pakker, versjoner => kontinuerlig
- Bruk av javascript for en startup
- Cross platform support med webteknologi
- Javascript i backend (NodeJS)
- Fra student i Trondheim til gründer i Trondheim
- Prototype vs production
- Historie: bytte av tredjepartskomponent med egen

**Comment by mikaelbr** [comment]
Hei! Flott 👌 

Hvilket tema tror jeg dere selv kan bestemme ut i fra hva dere motiveres av mest og hva dere blir engasjert av å snakke om.

Slik det ser ut nå vil det være januar som er mest aktuelt. Hva tenker dere om det?

**Comment by koiski** [comment]
@vegardbb bør vel svare på dette :)

**Comment by vegardbb** [comment]
Hei og hopp, allihopa! Jeg kan være med på podcasten i januar, og avvente for nærmere detaljer om dato.

**Comment by Krakels** [comment]
Hei! Jeg foreslår enten 7. eller 9. januar. Hvordan passer det for dere?

**Comment by vegardbb** [comment]
9. januar passer optimalt for min del.

**Comment by mikaelbr** [comment]
Da sier vi 9. januar! @vegardbb og @Krakels . Skal vi si 19:00 på Digs/Habitat?

**Comment by vegardbb** [comment]
JA, definitivt!

**Comment by mikaelbr** [comment]
@vegardbb Hva ble det landet på rundt tema? Kunne du ha skrevet en kjapp agenda for hva du ser for det vi kommer til å dekke?

**Comment by mikaelbr** [comment]
Blir det både @vegardbb og @koiski  eller bare @vegardbb ?

**Comment by vegardbb** [comment]
Hei, jeg tenker jeg møter opp på podcasten alene, siden Robin trolig blir opptatt både med app-utvikling og møter med kunder utover uka.

Den røde tråden jeg ser for meg er, for å sitere OP, **"Bruk av javascript for en startup"**, med fokus på NodeJS og npm. Jeg kan snakke utifra erfaringer jeg har som tjenesteutvikler for startupen. Utviklingsprosessen vår har innebært både bruk av tredjepartsmoduler og egenimplementerte løsninger.

**Comment by mikaelbr** [comment]
Den er god @vegardbb ! 👌 Høres bra ut. En ting jeg gjerne kunne tenkt meg er en setning om budskap. Det gjør det enklere for meg å tenke ut en slags oppnbygging/tankesett. Kunne du ha skrevet en setning eller to om hva du ønsker lyttere skal sitte igjen med etter episoden?

**Comment by vegardbb** [comment]
Jeg ønsker at lytterne tar med seg viten til å kunne avgjøre om de bør bruke en generell åpen-kildekode-tredjepartspakke fra npm til å realisere en webapplikasjon i sitt produksjon, eller om de bør skrive egen kode som løser deres spesifikke problemstilling, selv om det innebærer til dels å oppfinne hjulet på nytt. 

Jeg vil også at lytterne tar med seg viten om hvorvidt de bør bruke en ekstern SaaS-løsning som Okta til identitetshandtering eller skrive egen kode som løser deres spesifikke problemstilling (som f.eks hashing), selv om det igjen innebærer til dels å oppfinne hjulet på nytt (i tilfellet med identitetshandtering, sette opp egne ruter for POSTing av autentiseringsdata, skrive en funksjoner som hasher og salter passord korrekt, osv).

Hvis jeg skal formulere dette budskapet kortere, så er dette snakk om *prototyping og veien til en MVP*.

**Comment by vegardbb** [comment]
@mikaelbr, hvor i lokalet blir vi sittende?

**Comment by mikaelbr** [comment]
Det er nede i kjelleren bak en låst dør. Du kan møte opp på Habitat så kommer jeg og henter deg 👌

**Comment by vegardbb** [comment]
Så hvor i lokalet skal jeg stille meg?

**Comment by mikaelbr** [comment]
Bare stå ved trappen du. Jeg finner deg 👌

**Comment by vegardbb** [comment]
Mottatt.

**Comment by mikaelbr** [comment]
Vel gjennomført alle. Regner med at episoden kommer ila neste uke. Takk for denne gang og fin samtale, @vegardbb

**Comment by mikaelbr** [comment]
Episoden ligger ute på http://bartjs.io/episode-32-javascript-i-startups/
